# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00817d1c6baaf2631785976bd35258f369ab1ceb789701383be0e22413ad548d36372be0f92d8e6239edb096354cdf2247986b3a644e12e1bbc9df6164e07b81

test:
  secret_key_base: ce6a5cca749b1d770b368f5f8c6eb7c602786772364aa66a41929ad1e11e8532a4d15b9c6aca66ea62e63f1f909435427daccd25dc5c7528e6d3cee5e56e28ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
